# iOS Platform Configuration
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_DEPLOYMENT_TARGET "14.0")
set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET "14.0")

# Framework dependencies
find_library(COREAUDIO_FRAMEWORK CoreAudio)
find_library(COREMIDI_FRAMEWORK CoreMIDI)
find_library(AUDIOTOOLBOX_FRAMEWORK AudioToolbox)
find_library(AVFOUNDATION_FRAMEWORK AVFoundation)

set(IOS_FRAMEWORKS
    ${COREAUDIO_FRAMEWORK}
    ${COREMIDI_FRAMEWORK}
    ${AUDIOTOOLBOX_FRAMEWORK}
    ${AVFOUNDATION_FRAMEWORK}
)
